apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-loader-adapter
  namespace: realestatesrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-loader-adapter
  template:
    metadata:
      labels:
        app: content-loader-adapter
    spec:
      containers:
        - name: content-loader-adapter
          image: content-loader-adapter:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9094"
            - name: SERVER_PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: content-loader-adapter-service
  namespace: realestatesrm
spec:
  selector:
    app: content-loader-adapter
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP