apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-processor
  namespace: realestatesrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-processor
  template:
    metadata:
      labels:
        app: content-processor
    spec:
      containers:
        - name: content-processor
          image: content-processor:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9094"
            - name: SERVER_PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: content-processor-service
  namespace: realestatesrm
spec:
  selector:
    app: content-processor
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP