spring:

  kafka:
   bootstrap-servers: localhost:9094
   consumer:
    group-id: content-processor
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    max-poll-records: 50
   listener:
     type: batch

  datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: postgres
     driver-class-name: org.postgresql.Driver
